### ISSUE TITLE
gradle importable Spring boot example?

### ISSUE THREAD

**Issue by abeydemir23** [hotblac/windows-service-demo#1]
Hi @hotblac  I examined your work in this project, very good and explanatory example thanks. But I'm still wondering that could you provide this project as gradle project or could you give some hints about migrating this one to gradle?

**Comment by hotblac** [comment]
Sorry bud, I'm not familiar with Gradle so I can't offer much help. I don't intend to convert this to Gradle in the foreseeable future.
